/*사용자 테이블 */
CREATE TABLE TB_USER (
	ID VARCHAR2(100) PRIMARY KEY,
	NAME VARCHAR2(100) NOT NULL.
	PASSWORD VARCHAR2(50) NOT NULL.
	EMAIL VARCHAR2(100),
	PHONE_NO VARCHAR2(100),
	IS_ADMIN VARCHAR2(5),
	REGDATE DATE 	
);

/* 경력(이력) 테이블 */
CREATE TABLE TB_EXPS (
	NUM INT PRIMARY KEY,
	ID VARCHAR2(100) NOT NULL,
	POSITION VARCHAR2(100),
	PLACE VARCHAR2(100),
	EX_EXP CLOB,
	START_DATE DATE,
	END_DATE DATE
);

CREATE SEQUENCE EXPS_SEQ;


/* 교육사항 테이블 */
CREATE TABLE TB_EDU (
	NUM INT PRIMARY KEY,
	ID VARCHAR2(100) NOT NULL,
	PLACE VARCHAR2(100),
	MAJOR VARCHAR2(100),
	EDU_EXP CLOB,
	START_DATE DATE,
	END_DATE DATE
);

CREATE SEQUENCE EDU_SEQ;


/* 보유기술 테이블 */
CREATE TABLE TB_SKILLS (
	NUM INT PRIMARY KEY,
	ID VARCHAR2(100) NOT NULL,
	SKILL_NM VARCHAR2(50),
	SKILL_EXP CLOB
);

CREATE SEQUENCE SKILLS_SEQ;

/* 관심사 테이블 */
CREATE TABLE TB_INTS (
	NUM INT PRIMARY KEY,
	ID VARCHAR2(100) NOT NULL,
	INTS_NM VARCHAR2(50),
	INTS_EXP CLOB
);

CREATE SEQUENCE INTS_SEQ;

/* 수상 자격증 테이블 */
CREATE TABLE TB_AC (
	NUM INT PRIMARY KEY,
	ID VARCHAR2(100) NOT NULL,
	AC_NM VARCHAR2(50),
	AC_EXP CLOB,
	AC_DATE DATE
);

CREATE SEQUENCE AC_SEQ;


-- 비밀번호를 hash값으로 저장하기 위해 속성을 바꿈
ALTER TABLE TB_USER
MODIFY password VARCHAR2(200);